### ISSUE TITLE
Windows KERNELBASE exception and growing delay

### ISSUE THREAD

**Issue by chowchunkiu** [zeromq/clrzmq4#202]
Hi,

We are using the zmq library (libzmq-v140-x64-4_3_2) in a C# application, .Net framework v4.6.1, running on Windows Server 2012R2.  And we are facing 2 problems:

1. Sometimes the application crash suddenly, the event viewer saying "The process was terminated due to an unhandled exception; Faulting module name: KERNELBASE.dll, version: 6.3.9600.18666; Exception code: 0x40000015".  And in some cases, there is crash exception caught in the application saying the error is "System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.":
   at ZeroMQ.lib.zmq.zmq_msg_recv(IntPtr msg, IntPtr socket, Int32 flags)
   at ZeroMQ.ZSocket.ReceiveFrames[ListT](Int32& framesToReceive, ListT& frames, ZSocketFlags flags, ZError& error) in D:\Workspace\Core\clrzmq4\ZSocket.cs:line 536
   at ZeroMQ.ZSocket.ReceiveMessage(ZMessage& message, ZError& error) in D:\Workspace\Core\clrzmq4\ZSocket.cs:line 445

2. We found that the zmq socket sometimes send/recv with exceptionally large delay time, like sending and receiving over the AWS internal network the delay is around 100ms, but after a while for some unknown reason, the delay may start to grow, and keep growing up to seconds.  Restart the socket can sometimes help to bring the delay back to normal but does not always work.

Wish someone could give us some hints, thank you.

**Comment by kwinz** [comment]
Not seeing a reply to this well phrased bug report in over half a year makes me think this project is dead and best avoided.
